apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golang-application
  namespace: labs-argocd
spec:
  project: default
  source:
    helm: {}
    repoURL: "https://github.com/FWesleycosta/golang-application.git"
    path: helm
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: labs-argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
